config/routes.rb
require 'sidekiq/web'

NextUpChicago::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.instance_of?(AdminUser) }
  constraints constraint do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  get :buyer, to: "general#buyer"

  get :renter, to: "general#renter"

  get :properties, to: 'properties#index'

  resources :guides, only: [:index, :show] do
  end

  resources :contact, only: [:index, :create] do
    get :confirmation, on: :collection
  end

  %w[about_us press careers].each do |company_page|
    get company_page.gsub('_', '-') => "company##{company_page}", as: company_page
  end

  root to: 'general#index'

end

app/models/about_us.rb
class AboutUs

  include Mongoid::Document
  include Mongoid::Timestamps

  field :title
  field :info

  field :realtor_name
  field :realtor_bio
  field :realtor_email
  field :realtor_phone

  mount_uploader :realtor_picture,  RealtorPicUploader

  attr_accessible :title, :info, :realtor_name, :realtor_bio, :realtor_email, :realtor_phone, :realtor_picture, :realtor_picture_cache

  def self.get_page
    about_us = AboutUs.all.first
    if about_us.nil?
      about_us = AboutUs.create!
    end
    about_us
  end


end

app/models/admin_user.rb
class AdminUser
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/models/contact.rb
class Contact

  include Mongoid::Document
  include Mongoid::Timestamps

  field :name
  field :email
  field :subject
  field :body
  field :about

  attr_accessor :name, :email, :subject, :body, :about

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => false

end

app/models/contact_us_form.rb
class ContactUsForm
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => false

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/feature_building.rb
class FeatureBuilding

  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug

  field :name
  field :address_1
  field :address_2
  field :city
  field :state
  field :zip
  field :info
  field :rental,    type: Boolean, default: false

  mount_uploader :building_pic, BuildingPicUploader

  slug :name

  attr_accessible :name, :address_1, :address_2, :city, :state,
  :zip, :info, :rental, :building_pic, :building_pic_cache


end

app/models/press.rb
class Press

  include Mongoid::Document
  include Mongoid::Timestamps

  field :title
  field :snippet
  field :link

  mount_uploader :press_pic, PressPicUploader

  attr_accessible :title, :snippet, :link, :press_pic, :press_pic_cache


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController

  def about_us
  end

  def team
  end

  def careers
  end


end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index
    @contact_us_form = Contact.new
  end

  def create
    @contact_us_form = Contact.new(params[:contact_us_form])

    if @contact_us_form.valid?
      @contact_us_form.save
      # ContactMailer.new_message(@contact_us_form).deliver
      redirect_to confirmation_contact_us_path
    else
      flash.now.alert = "Please fill out all fields."
      render new_contact_us_path
    end
  end

  def confirmation
  end

end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController

  def index
    @contact_us_form = ContactUsForm.new
  end

  def create
    @contact_us_form = ContactUsForm.new(params[:contact_us_form])

    if @contact_us_form.valid?
      ContactMailer.new_message(@contact_us_form).deliver
      redirect_to confirmation_contact_us_path
    else
      flash.now.alert = "Please fill out all fields."
      render new_contact_us_path
    end
  end

  def confirmation
  end

end

app/controllers/general_controller.rb
class GeneralController < ApplicationController

  def index
  end

  def buyer
  end

  def renter
  end

end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController

  def index
  end

  def show
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def cc_html(options = {}, &blk)
    attrs = options.map { |(k, v)| %( #{h k}="#{h v}") }.join('')
    [ %(<!--[if lt IE 7 ]><html#{attrs} class="ie6"><![endif]-->),
      %(<!--[if IE 7 ]><html#{attrs} class="ie7"><![endif]-->),
      %(<!--[if IE 8 ]><html#{attrs} class="ie8"><![endif]-->),
      %(<!--[if IE 8 ]><html#{attrs} class="ie9"><![endif]-->),
      %(<!--[if (gt IE 9)|!(IE)]><!--><html#{attrs}><!--<![endif]-->),
      capture_haml(&blk).strip,
      "</html>"
    ].join("\n")
  end
  def flash_type(type)
    case type
    when :alert
      'alert-block'
    when :error
      'alert-error'
    when :notice
      'alert-info'
    when :success
      'alert-success'
    else
      type.to_s
    end
  end
  def next_up_current_page?(url1, url2)
    is_current_page = false
    if current_page?(url1)
      is_current_page = true
    end
    if current_page?(url2)
      is_current_page = true
    end
    is_current_page
  end
end

app/helpers/layout_helper.rb
module LayoutHelper
  def title(page_title=nil, show_title = true)
    content_for(:title) { h(page_title.to_s) } unless page_title.nil?
  end

  def stylesheet(*args)
    content_for(:stylesheets) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:javascript) { javascript_include_tag(*args) }
  end

end

app/views/layouts/application.html.haml
!!! 5
!= cc_html(:lang => "en") do
  = render :partial => "shared/head"
  %body
    = render :partial => "shared/header"
    = yield

    = render :partial => "shared/footer"

    - if ENV['RAILS_ENV'] == 'development'
      = render :partial => "shared/debug_console"
    = render :partial => "shared/javascripts"

app/views/shared/_debug_console.html.haml
.container
  .hero-unit.white
    %ul
      - session.each do |var|
        %li
          = var.inspect
    = yield :debug

app/views/shared/_footer.html.haml
.container
  .row
    .span12
      / %hr
      %footer
        %p.pull-left &copy; Next Up Chicago 2013
  .row
    .span3
      %h4 Pages
      %ul.unstyled
        %li
          = link_to "Buyer", buyer_path
        %li
          = link_to "Renter", renter_path
        %li
          = link_to "Guides", guides_path
    .span3
      %h4 Company
      %ul.unstyled
        %li
          = link_to "About Us", about_us_path
        %li
          = link_to "Press", press_path
        %li
          = link_to "Careers", careers_path
    .span2.offset4
      %address
        %strong Next Up Chicago
        %br
        123 Randolph St
        %br
        Chicago, IL 60607
        %br
        %abbr{title: "Phone"} P:
        (123) 456-7890

app/views/shared/_head.html.haml
%head
  %title= content_for?(:title) ? yield(:title) + ' - Next Up Chicago' : 'Next Up Chicago'
  = csrf_meta_tags
  %meta{ charset: 'utf-8' }
  %meta{ 'http-equiv' => 'X-UA-Compatible', content: 'IE=edge,chrome=1' }
  %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }
  %meta{ name: "apple-mobile-web-app-capable", content: "yes" }


  = stylesheet_link_tag "application", :media => "all"
  = yield(:stylesheets)

app/views/shared/_header.html.haml
.jumbotron
  .container
    %p Next Up Chicago

.container
  .navbar
    .navbar-inner
      .nav
        %li{class: (current_page?(root_path) ? "active" : "")}
          = link_to "Home", root_path
        %li{class: (current_page?(properties_path) ? "active" : "")}
          = link_to "Properties", properties_path
        %li{class: (current_page?(guides_path) ? "active" : "")}
          = link_to "Guides", guides_path
        %li{class: (current_page?(about_us_path) ? "active" : "")}
          = link_to "About Us", about_us_path
        %li{class: (current_page?(contact_index_path) ? "active" : "")}
          = link_to "Contact Us", contact_index_path

app/views/shared/_javascripts.html.haml
= javascript_include_tag "application"

- if Rails.env.production?
  :javascript



= yield(:javascript)

app/views/shared/_messages.html.haml
- flash.each do |type, message|
  .alert.alert-message.fade.in{ 'data-alert' => 'alert', class: flash_type(type) }
    %button.close{ "data-dismiss" => "alert" } ×

    - if message.is_a?(Array)
      - if message.length == 1
        %h5= message.first
      - else
        %h5 Please correct the following errors:
        %ul
          - message.each do |individual_message|
            %li= individual_message
    - else
      %h5= message